### PR TITLE
I created form for email verification

### PR DESCRIPTION
**Pull request by thewebsource**
I have to create a form for email verification in the email_verify.html. in the file i have to create a form tag inside form tag i have to create on input tag and one button tag.

### CODE REVIEW

**Review by Devsantoshkumar — COMMENTED** [review]
add one more line for phone number input field

**Comment by thewebsource** [comment]
okay

**Review by Devsantoshkumar — CHANGES_REQUESTED** [review]
change submit button with input submit

**Review by Devsantoshkumar — APPROVED** [review]
okay done i am mergin you changes. thank you

**Pull request merged**
